### ISSUE TITLE
Api error

### ISSUE THREAD

**Issue by RyanManchikanti** [ahmedbesbes/cartoonify#2]
After following everything described in the tutorial , i finally got a url after deploying sls model.
when i pasted that url in notebooks an executed the code i kept getting this error, any help is much appreciated , i'm very close to completing this project i need help with this error.

KeyError: 'output'
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-17-c34decdae6fe> in <module>
----> 1 image = response.json()["output"]
      2 
      3 image = image[image.find(",")+1:]
      4 dec = base64.b64decode(image + "===")
      5 
KeyError: 'output'

**Comment by ahmedbesbes** [comment]
duplicate [here](https://github.com/ahmedbesbes/cartoonify/issues/4) . closing this issue
